FROM python:3.12.6

WORKDIR /workspace
COPY . /workspace

ENV API_URL="https://u8whitimu7.execute-api.ap-southeast-1.amazonaws.com/prod"

RUN pip install -r requirements.txt

ENTRYPOINT ["python", "main.py"]